# Generated by Django 3.0.3 on 2020-02-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
