# Generated by Django 3.0.3 on 2020-02-09 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.CharField(default='This is the first answer', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='voted_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='modified',
            field=models.DateTimeField(blank=True),
        ),
    ]
