# Generated by Django 3.0.3 on 2020-02-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200209_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='modified',
            field=models.DateTimeField(blank=True),
        ),
    ]
