# Generated by Django 3.0.3 on 2020-02-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20200209_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_choices',
            field=models.BooleanField(default=False),
        ),
    ]
